// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_BUCKET: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
}
