name = "cf-backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"


[observability.logs]
enabled = true


[placement]
mode = "smart"

[ai]
binding = "AI"

[env.production]
name = "cf-backend-prod"

routes = [
  { pattern = "api.studyboost.org", custom_domain = true }
]

[env.production.ai]
binding = "AI"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "studyboost-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "studyboost-db-prod"
database_id = "d2cb7781-1012-42e8-a2ac-c944de4c9617"

[[env.production.r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "studyboost-prod"

[env.dev]
name = "cf-backend-dev"

[env.dev.ai]
binding = "AI"

[[env.dev.vectorize]]
binding = "VECTORIZE"
index_name = "studyninja-test"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "studyboost-dev"
database_id = "2ea09955-74a8-4ed7-9f93-79318792bf5a"

[[env.dev.r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "studymore-dev"
preview_bucket_name = "studymore-test"



